- name: Exploring webhooks
  connection: local
  hosts: localhost
  
  tasks:
  - name: print to the screen
    debug:
        msg: "Don/kleewyck  webhook just ran!"

  - name: print to the screen
    debug:
        msg: "Another Task"


